# Generated by Django 4.1.7 on 2023-03-29 05:07

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='pokemon',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(max_length=45, unique=True)),
                ('nombre', models.CharField(max_length=150)),
                ('elemento', models.CharField(max_length=150)),
                ('genero', models.CharField(max_length=150)),
                ('estado', models.CharField(max_length=150)),
            ],
        ),
    ]
